// <auto-generated />
using System;
using GeoSquirrelApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeoSquirrelApi.Migrations
{
    [DbContext(typeof(GeoSquirrelApiContext))]
    [Migration("20210125194422_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeoSquirrelApi.Models.Cache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<decimal>("Latitude");

                    b.Property<decimal>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("CacheId");

                    b.ToTable("Caches");

                    b.HasData(
                        new
                        {
                            CacheId = 1,
                            DateCreated = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 17.88888888m,
                            Longitude = 7.58888855m,
                            Name = "Location 1"
                        },
                        new
                        {
                            CacheId = 2,
                            DateCreated = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 20.88888888m,
                            Longitude = 10.58888855m,
                            Name = "Location 2"
                        },
                        new
                        {
                            CacheId = 3,
                            DateCreated = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 23.88888888m,
                            Longitude = 13.55888885m,
                            Name = "Location 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
